[tool.poetry]
name = "passgen"
version = "2.0.0"
description = "A simple service for generating passwords with guaranteed presence of uppercase and lowercase letters, numbers and special characters."
authors = ["Dmitrii Zakharov <dmitrii@zakharov.cc>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
aiohttp = "3.7.4.post0"
aiohttp_cors = "0.7.0"
gunicorn = "20.0.4"
certifi = "2020.12.5"

[tool.poetry.dev-dependencies]
pytest-aiohttp = "0.3.0"
aiohttp-devtools = "0.13.1"
pytest-cov = "2.11.1"
coveralls = "3.0.1"
flake8 = "3.9.0"
pytest = "6.2.2"
black = "20.8b1"
isort = "5.7.0"
bandit = "1.7.0"
safety = "1.10.3"
mypy = "0.812"
pydocstyle = "5.1.1"

[tool.black]
skip-string-normalization = 1

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
